package com.LTNC.LTNC_Java.mapper;

import com.LTNC.LTNC_Java.model.Anh;
import com.LTNC.LTNC_Java.model.AnhExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AnhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    long countByExample(AnhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByExample(AnhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByPrimaryKey(Integer idanh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insert(Anh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insertSelective(Anh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    List<Anh> selectByExample(AnhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    Anh selectByPrimaryKey(Integer idanh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExampleSelective(@Param("record") Anh record, @Param("example") AnhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExample(@Param("record") Anh record, @Param("example") AnhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKeySelective(Anh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKey(Anh record);
}