package com.LTNC.LTNC_Java.mapper;

import com.LTNC.LTNC_Java.model.DonHang;
import com.LTNC.LTNC_Java.model.DonHangExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface DonHangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    long countByExample(DonHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByExample(DonHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByPrimaryKey(Integer iddon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insert(DonHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insertSelective(DonHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    List<DonHang> selectByExample(DonHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    DonHang selectByPrimaryKey(Integer iddon);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExampleSelective(@Param("record") DonHang record, @Param("example") DonHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExample(@Param("record") DonHang record, @Param("example") DonHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKeySelective(DonHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKey(DonHang record);
}