package com.LTNC.LTNC_Java.mapper;

import com.LTNC.LTNC_Java.model.KhachHang;
import com.LTNC.LTNC_Java.model.KhachHangExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface KhachHangMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    long countByExample(KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByExample(KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByPrimaryKey(Integer idkhach);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insert(KhachHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insertSelective(KhachHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    List<KhachHang> selectByExample(KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    KhachHang selectByPrimaryKey(Integer idkhach);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExampleSelective(@Param("record") KhachHang record, @Param("example") KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExample(@Param("record") KhachHang record, @Param("example") KhachHangExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKeySelective(KhachHang record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKey(KhachHang record);
}