package com.LTNC.LTNC_Java.mapper;

import com.LTNC.LTNC_Java.model.LoaiSp;
import com.LTNC.LTNC_Java.model.LoaiSpExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface LoaiSpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    long countByExample(LoaiSpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByExample(LoaiSpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByPrimaryKey(Integer idloai);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insert(LoaiSp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insertSelective(LoaiSp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    List<LoaiSp> selectByExample(LoaiSpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    LoaiSp selectByPrimaryKey(Integer idloai);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExampleSelective(@Param("record") LoaiSp record, @Param("example") LoaiSpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExample(@Param("record") LoaiSp record, @Param("example") LoaiSpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKeySelective(LoaiSp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKey(LoaiSp record);
}