package com.LTNC.LTNC_Java.mapper;

import com.LTNC.LTNC_Java.model.SanPham;
import com.LTNC.LTNC_Java.model.SanPhamExample;
import com.LTNC.LTNC_Java.model.SanPhamWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SanPhamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    long countByExample(SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByExample(SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int deleteByPrimaryKey(Integer idsp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insert(SanPhamWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int insertSelective(SanPhamWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    List<SanPhamWithBLOBs> selectByExampleWithBLOBs(SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    List<SanPham> selectByExample(SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    SanPhamWithBLOBs selectByPrimaryKey(Integer idsp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExampleSelective(@Param("record") SanPhamWithBLOBs record, @Param("example") SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExampleWithBLOBs(@Param("record") SanPhamWithBLOBs record, @Param("example") SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByExample(@Param("record") SanPham record, @Param("example") SanPhamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKeySelective(SanPhamWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKeyWithBLOBs(SanPhamWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SanPham
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    int updateByPrimaryKey(SanPham record);
}