package com.LTNC.LTNC_Java.model;

public class Anh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Anh.idAnh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idanh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Anh.link
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Anh.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idsp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Anh.idAnh
     *
     * @return the value of Anh.idAnh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdanh() {
        return idanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Anh.idAnh
     *
     * @param idanh the value for Anh.idAnh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdanh(Integer idanh) {
        this.idanh = idanh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Anh.link
     *
     * @return the value of Anh.link
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Anh.link
     *
     * @param link the value for Anh.link
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Anh.idSp
     *
     * @return the value of Anh.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdsp() {
        return idsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Anh.idSp
     *
     * @param idsp the value for Anh.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdsp(Integer idsp) {
        this.idsp = idsp;
    }
}