package com.LTNC.LTNC_Java.model;

public class CT_DonHangKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CT_DonHang.idDon
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iddon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CT_DonHang.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idsp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CT_DonHang.idDon
     *
     * @return the value of CT_DonHang.idDon
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIddon() {
        return iddon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CT_DonHang.idDon
     *
     * @param iddon the value for CT_DonHang.idDon
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIddon(Integer iddon) {
        this.iddon = iddon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CT_DonHang.idSp
     *
     * @return the value of CT_DonHang.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdsp() {
        return idsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CT_DonHang.idSp
     *
     * @param idsp the value for CT_DonHang.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdsp(Integer idsp) {
        this.idsp = idsp;
    }
}