package com.LTNC.LTNC_Java.model;

import java.util.Date;

public class DonHang {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.idDon
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iddon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.ngayDat
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Date ngaydat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.diaChiGiao
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String diachigiao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.moTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String mota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.tongTien
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Double tongtien;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idkhach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DonHang.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Boolean trangthai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.idDon
     *
     * @return the value of DonHang.idDon
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIddon() {
        return iddon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.idDon
     *
     * @param iddon the value for DonHang.idDon
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIddon(Integer iddon) {
        this.iddon = iddon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.ngayDat
     *
     * @return the value of DonHang.ngayDat
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Date getNgaydat() {
        return ngaydat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.ngayDat
     *
     * @param ngaydat the value for DonHang.ngayDat
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setNgaydat(Date ngaydat) {
        this.ngaydat = ngaydat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.diaChiGiao
     *
     * @return the value of DonHang.diaChiGiao
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getDiachigiao() {
        return diachigiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.diaChiGiao
     *
     * @param diachigiao the value for DonHang.diaChiGiao
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setDiachigiao(String diachigiao) {
        this.diachigiao = diachigiao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.moTa
     *
     * @return the value of DonHang.moTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getMota() {
        return mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.moTa
     *
     * @param mota the value for DonHang.moTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setMota(String mota) {
        this.mota = mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.tongTien
     *
     * @return the value of DonHang.tongTien
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Double getTongtien() {
        return tongtien;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.tongTien
     *
     * @param tongtien the value for DonHang.tongTien
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTongtien(Double tongtien) {
        this.tongtien = tongtien;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.idKhach
     *
     * @return the value of DonHang.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdkhach() {
        return idkhach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.idKhach
     *
     * @param idkhach the value for DonHang.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdkhach(Integer idkhach) {
        this.idkhach = idkhach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.idUser
     *
     * @return the value of DonHang.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.idUser
     *
     * @param iduser the value for DonHang.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DonHang.trangThai
     *
     * @return the value of DonHang.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Boolean getTrangthai() {
        return trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DonHang.trangThai
     *
     * @param trangthai the value for DonHang.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTrangthai(Boolean trangthai) {
        this.trangthai = trangthai;
    }
}