package com.LTNC.LTNC_Java.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DonHangExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public DonHangExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIddonIsNull() {
            addCriterion("idDon is null");
            return (Criteria) this;
        }

        public Criteria andIddonIsNotNull() {
            addCriterion("idDon is not null");
            return (Criteria) this;
        }

        public Criteria andIddonEqualTo(Integer value) {
            addCriterion("idDon =", value, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonNotEqualTo(Integer value) {
            addCriterion("idDon <>", value, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonGreaterThan(Integer value) {
            addCriterion("idDon >", value, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonGreaterThanOrEqualTo(Integer value) {
            addCriterion("idDon >=", value, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonLessThan(Integer value) {
            addCriterion("idDon <", value, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonLessThanOrEqualTo(Integer value) {
            addCriterion("idDon <=", value, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonIn(List<Integer> values) {
            addCriterion("idDon in", values, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonNotIn(List<Integer> values) {
            addCriterion("idDon not in", values, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonBetween(Integer value1, Integer value2) {
            addCriterion("idDon between", value1, value2, "iddon");
            return (Criteria) this;
        }

        public Criteria andIddonNotBetween(Integer value1, Integer value2) {
            addCriterion("idDon not between", value1, value2, "iddon");
            return (Criteria) this;
        }

        public Criteria andNgaydatIsNull() {
            addCriterion("ngayDat is null");
            return (Criteria) this;
        }

        public Criteria andNgaydatIsNotNull() {
            addCriterion("ngayDat is not null");
            return (Criteria) this;
        }

        public Criteria andNgaydatEqualTo(Date value) {
            addCriterion("ngayDat =", value, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatNotEqualTo(Date value) {
            addCriterion("ngayDat <>", value, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatGreaterThan(Date value) {
            addCriterion("ngayDat >", value, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatGreaterThanOrEqualTo(Date value) {
            addCriterion("ngayDat >=", value, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatLessThan(Date value) {
            addCriterion("ngayDat <", value, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatLessThanOrEqualTo(Date value) {
            addCriterion("ngayDat <=", value, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatIn(List<Date> values) {
            addCriterion("ngayDat in", values, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatNotIn(List<Date> values) {
            addCriterion("ngayDat not in", values, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatBetween(Date value1, Date value2) {
            addCriterion("ngayDat between", value1, value2, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andNgaydatNotBetween(Date value1, Date value2) {
            addCriterion("ngayDat not between", value1, value2, "ngaydat");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoIsNull() {
            addCriterion("diaChiGiao is null");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoIsNotNull() {
            addCriterion("diaChiGiao is not null");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoEqualTo(String value) {
            addCriterion("diaChiGiao =", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoNotEqualTo(String value) {
            addCriterion("diaChiGiao <>", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoGreaterThan(String value) {
            addCriterion("diaChiGiao >", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoGreaterThanOrEqualTo(String value) {
            addCriterion("diaChiGiao >=", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoLessThan(String value) {
            addCriterion("diaChiGiao <", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoLessThanOrEqualTo(String value) {
            addCriterion("diaChiGiao <=", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoLike(String value) {
            addCriterion("diaChiGiao like", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoNotLike(String value) {
            addCriterion("diaChiGiao not like", value, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoIn(List<String> values) {
            addCriterion("diaChiGiao in", values, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoNotIn(List<String> values) {
            addCriterion("diaChiGiao not in", values, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoBetween(String value1, String value2) {
            addCriterion("diaChiGiao between", value1, value2, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andDiachigiaoNotBetween(String value1, String value2) {
            addCriterion("diaChiGiao not between", value1, value2, "diachigiao");
            return (Criteria) this;
        }

        public Criteria andMotaIsNull() {
            addCriterion("moTa is null");
            return (Criteria) this;
        }

        public Criteria andMotaIsNotNull() {
            addCriterion("moTa is not null");
            return (Criteria) this;
        }

        public Criteria andMotaEqualTo(String value) {
            addCriterion("moTa =", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotEqualTo(String value) {
            addCriterion("moTa <>", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaGreaterThan(String value) {
            addCriterion("moTa >", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaGreaterThanOrEqualTo(String value) {
            addCriterion("moTa >=", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaLessThan(String value) {
            addCriterion("moTa <", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaLessThanOrEqualTo(String value) {
            addCriterion("moTa <=", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaLike(String value) {
            addCriterion("moTa like", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotLike(String value) {
            addCriterion("moTa not like", value, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaIn(List<String> values) {
            addCriterion("moTa in", values, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotIn(List<String> values) {
            addCriterion("moTa not in", values, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaBetween(String value1, String value2) {
            addCriterion("moTa between", value1, value2, "mota");
            return (Criteria) this;
        }

        public Criteria andMotaNotBetween(String value1, String value2) {
            addCriterion("moTa not between", value1, value2, "mota");
            return (Criteria) this;
        }

        public Criteria andTongtienIsNull() {
            addCriterion("tongTien is null");
            return (Criteria) this;
        }

        public Criteria andTongtienIsNotNull() {
            addCriterion("tongTien is not null");
            return (Criteria) this;
        }

        public Criteria andTongtienEqualTo(Double value) {
            addCriterion("tongTien =", value, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienNotEqualTo(Double value) {
            addCriterion("tongTien <>", value, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienGreaterThan(Double value) {
            addCriterion("tongTien >", value, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienGreaterThanOrEqualTo(Double value) {
            addCriterion("tongTien >=", value, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienLessThan(Double value) {
            addCriterion("tongTien <", value, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienLessThanOrEqualTo(Double value) {
            addCriterion("tongTien <=", value, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienIn(List<Double> values) {
            addCriterion("tongTien in", values, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienNotIn(List<Double> values) {
            addCriterion("tongTien not in", values, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienBetween(Double value1, Double value2) {
            addCriterion("tongTien between", value1, value2, "tongtien");
            return (Criteria) this;
        }

        public Criteria andTongtienNotBetween(Double value1, Double value2) {
            addCriterion("tongTien not between", value1, value2, "tongtien");
            return (Criteria) this;
        }

        public Criteria andIdkhachIsNull() {
            addCriterion("idKhach is null");
            return (Criteria) this;
        }

        public Criteria andIdkhachIsNotNull() {
            addCriterion("idKhach is not null");
            return (Criteria) this;
        }

        public Criteria andIdkhachEqualTo(Integer value) {
            addCriterion("idKhach =", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachNotEqualTo(Integer value) {
            addCriterion("idKhach <>", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachGreaterThan(Integer value) {
            addCriterion("idKhach >", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachGreaterThanOrEqualTo(Integer value) {
            addCriterion("idKhach >=", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachLessThan(Integer value) {
            addCriterion("idKhach <", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachLessThanOrEqualTo(Integer value) {
            addCriterion("idKhach <=", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachIn(List<Integer> values) {
            addCriterion("idKhach in", values, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachNotIn(List<Integer> values) {
            addCriterion("idKhach not in", values, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachBetween(Integer value1, Integer value2) {
            addCriterion("idKhach between", value1, value2, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachNotBetween(Integer value1, Integer value2) {
            addCriterion("idKhach not between", value1, value2, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIduserIsNull() {
            addCriterion("idUser is null");
            return (Criteria) this;
        }

        public Criteria andIduserIsNotNull() {
            addCriterion("idUser is not null");
            return (Criteria) this;
        }

        public Criteria andIduserEqualTo(Integer value) {
            addCriterion("idUser =", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotEqualTo(Integer value) {
            addCriterion("idUser <>", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserGreaterThan(Integer value) {
            addCriterion("idUser >", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserGreaterThanOrEqualTo(Integer value) {
            addCriterion("idUser >=", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserLessThan(Integer value) {
            addCriterion("idUser <", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserLessThanOrEqualTo(Integer value) {
            addCriterion("idUser <=", value, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserIn(List<Integer> values) {
            addCriterion("idUser in", values, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotIn(List<Integer> values) {
            addCriterion("idUser not in", values, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserBetween(Integer value1, Integer value2) {
            addCriterion("idUser between", value1, value2, "iduser");
            return (Criteria) this;
        }

        public Criteria andIduserNotBetween(Integer value1, Integer value2) {
            addCriterion("idUser not between", value1, value2, "iduser");
            return (Criteria) this;
        }

        public Criteria andTrangthaiIsNull() {
            addCriterion("trangThai is null");
            return (Criteria) this;
        }

        public Criteria andTrangthaiIsNotNull() {
            addCriterion("trangThai is not null");
            return (Criteria) this;
        }

        public Criteria andTrangthaiEqualTo(Boolean value) {
            addCriterion("trangThai =", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiNotEqualTo(Boolean value) {
            addCriterion("trangThai <>", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiGreaterThan(Boolean value) {
            addCriterion("trangThai >", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiGreaterThanOrEqualTo(Boolean value) {
            addCriterion("trangThai >=", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiLessThan(Boolean value) {
            addCriterion("trangThai <", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiLessThanOrEqualTo(Boolean value) {
            addCriterion("trangThai <=", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiIn(List<Boolean> values) {
            addCriterion("trangThai in", values, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiNotIn(List<Boolean> values) {
            addCriterion("trangThai not in", values, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiBetween(Boolean value1, Boolean value2) {
            addCriterion("trangThai between", value1, value2, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiNotBetween(Boolean value1, Boolean value2) {
            addCriterion("trangThai not between", value1, value2, "trangthai");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DonHang
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 04 22:35:50 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DonHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}