package com.LTNC.LTNC_Java.model;

public class KhachHang {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idkhach;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.hoTen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String hoten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.diaChi
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String diachi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.email
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.sdt
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String sdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.tenDangNhap
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String tendangnhap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.matKhau
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String matkhau;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KhachHang.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Boolean trangthai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.idKhach
     *
     * @return the value of KhachHang.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdkhach() {
        return idkhach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.idKhach
     *
     * @param idkhach the value for KhachHang.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdkhach(Integer idkhach) {
        this.idkhach = idkhach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.hoTen
     *
     * @return the value of KhachHang.hoTen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getHoten() {
        return hoten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.hoTen
     *
     * @param hoten the value for KhachHang.hoTen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.diaChi
     *
     * @return the value of KhachHang.diaChi
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getDiachi() {
        return diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.diaChi
     *
     * @param diachi the value for KhachHang.diaChi
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.email
     *
     * @return the value of KhachHang.email
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.email
     *
     * @param email the value for KhachHang.email
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.sdt
     *
     * @return the value of KhachHang.sdt
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.sdt
     *
     * @param sdt the value for KhachHang.sdt
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.tenDangNhap
     *
     * @return the value of KhachHang.tenDangNhap
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTendangnhap() {
        return tendangnhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.tenDangNhap
     *
     * @param tendangnhap the value for KhachHang.tenDangNhap
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.matKhau
     *
     * @return the value of KhachHang.matKhau
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getMatkhau() {
        return matkhau;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.matKhau
     *
     * @param matkhau the value for KhachHang.matKhau
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KhachHang.trangThai
     *
     * @return the value of KhachHang.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Boolean getTrangthai() {
        return trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KhachHang.trangThai
     *
     * @param trangthai the value for KhachHang.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTrangthai(Boolean trangthai) {
        this.trangthai = trangthai;
    }
}