package com.LTNC.LTNC_Java.model;

import java.util.ArrayList;
import java.util.List;

public class KhachHangExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public KhachHangExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdkhachIsNull() {
            addCriterion("idKhach is null");
            return (Criteria) this;
        }

        public Criteria andIdkhachIsNotNull() {
            addCriterion("idKhach is not null");
            return (Criteria) this;
        }

        public Criteria andIdkhachEqualTo(Integer value) {
            addCriterion("idKhach =", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachNotEqualTo(Integer value) {
            addCriterion("idKhach <>", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachGreaterThan(Integer value) {
            addCriterion("idKhach >", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachGreaterThanOrEqualTo(Integer value) {
            addCriterion("idKhach >=", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachLessThan(Integer value) {
            addCriterion("idKhach <", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachLessThanOrEqualTo(Integer value) {
            addCriterion("idKhach <=", value, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachIn(List<Integer> values) {
            addCriterion("idKhach in", values, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachNotIn(List<Integer> values) {
            addCriterion("idKhach not in", values, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachBetween(Integer value1, Integer value2) {
            addCriterion("idKhach between", value1, value2, "idkhach");
            return (Criteria) this;
        }

        public Criteria andIdkhachNotBetween(Integer value1, Integer value2) {
            addCriterion("idKhach not between", value1, value2, "idkhach");
            return (Criteria) this;
        }

        public Criteria andHotenIsNull() {
            addCriterion("hoTen is null");
            return (Criteria) this;
        }

        public Criteria andHotenIsNotNull() {
            addCriterion("hoTen is not null");
            return (Criteria) this;
        }

        public Criteria andHotenEqualTo(String value) {
            addCriterion("hoTen =", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotEqualTo(String value) {
            addCriterion("hoTen <>", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenGreaterThan(String value) {
            addCriterion("hoTen >", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenGreaterThanOrEqualTo(String value) {
            addCriterion("hoTen >=", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLessThan(String value) {
            addCriterion("hoTen <", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLessThanOrEqualTo(String value) {
            addCriterion("hoTen <=", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenLike(String value) {
            addCriterion("hoTen like", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotLike(String value) {
            addCriterion("hoTen not like", value, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenIn(List<String> values) {
            addCriterion("hoTen in", values, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotIn(List<String> values) {
            addCriterion("hoTen not in", values, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenBetween(String value1, String value2) {
            addCriterion("hoTen between", value1, value2, "hoten");
            return (Criteria) this;
        }

        public Criteria andHotenNotBetween(String value1, String value2) {
            addCriterion("hoTen not between", value1, value2, "hoten");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNull() {
            addCriterion("diaChi is null");
            return (Criteria) this;
        }

        public Criteria andDiachiIsNotNull() {
            addCriterion("diaChi is not null");
            return (Criteria) this;
        }

        public Criteria andDiachiEqualTo(String value) {
            addCriterion("diaChi =", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotEqualTo(String value) {
            addCriterion("diaChi <>", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThan(String value) {
            addCriterion("diaChi >", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiGreaterThanOrEqualTo(String value) {
            addCriterion("diaChi >=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThan(String value) {
            addCriterion("diaChi <", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLessThanOrEqualTo(String value) {
            addCriterion("diaChi <=", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiLike(String value) {
            addCriterion("diaChi like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotLike(String value) {
            addCriterion("diaChi not like", value, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiIn(List<String> values) {
            addCriterion("diaChi in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotIn(List<String> values) {
            addCriterion("diaChi not in", values, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiBetween(String value1, String value2) {
            addCriterion("diaChi between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andDiachiNotBetween(String value1, String value2) {
            addCriterion("diaChi not between", value1, value2, "diachi");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andSdtIsNull() {
            addCriterion("sdt is null");
            return (Criteria) this;
        }

        public Criteria andSdtIsNotNull() {
            addCriterion("sdt is not null");
            return (Criteria) this;
        }

        public Criteria andSdtEqualTo(String value) {
            addCriterion("sdt =", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotEqualTo(String value) {
            addCriterion("sdt <>", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtGreaterThan(String value) {
            addCriterion("sdt >", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtGreaterThanOrEqualTo(String value) {
            addCriterion("sdt >=", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLessThan(String value) {
            addCriterion("sdt <", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLessThanOrEqualTo(String value) {
            addCriterion("sdt <=", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtLike(String value) {
            addCriterion("sdt like", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotLike(String value) {
            addCriterion("sdt not like", value, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtIn(List<String> values) {
            addCriterion("sdt in", values, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotIn(List<String> values) {
            addCriterion("sdt not in", values, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtBetween(String value1, String value2) {
            addCriterion("sdt between", value1, value2, "sdt");
            return (Criteria) this;
        }

        public Criteria andSdtNotBetween(String value1, String value2) {
            addCriterion("sdt not between", value1, value2, "sdt");
            return (Criteria) this;
        }

        public Criteria andTendangnhapIsNull() {
            addCriterion("tenDangNhap is null");
            return (Criteria) this;
        }

        public Criteria andTendangnhapIsNotNull() {
            addCriterion("tenDangNhap is not null");
            return (Criteria) this;
        }

        public Criteria andTendangnhapEqualTo(String value) {
            addCriterion("tenDangNhap =", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapNotEqualTo(String value) {
            addCriterion("tenDangNhap <>", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapGreaterThan(String value) {
            addCriterion("tenDangNhap >", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapGreaterThanOrEqualTo(String value) {
            addCriterion("tenDangNhap >=", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapLessThan(String value) {
            addCriterion("tenDangNhap <", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapLessThanOrEqualTo(String value) {
            addCriterion("tenDangNhap <=", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapLike(String value) {
            addCriterion("tenDangNhap like", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapNotLike(String value) {
            addCriterion("tenDangNhap not like", value, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapIn(List<String> values) {
            addCriterion("tenDangNhap in", values, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapNotIn(List<String> values) {
            addCriterion("tenDangNhap not in", values, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapBetween(String value1, String value2) {
            addCriterion("tenDangNhap between", value1, value2, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andTendangnhapNotBetween(String value1, String value2) {
            addCriterion("tenDangNhap not between", value1, value2, "tendangnhap");
            return (Criteria) this;
        }

        public Criteria andMatkhauIsNull() {
            addCriterion("matKhau is null");
            return (Criteria) this;
        }

        public Criteria andMatkhauIsNotNull() {
            addCriterion("matKhau is not null");
            return (Criteria) this;
        }

        public Criteria andMatkhauEqualTo(String value) {
            addCriterion("matKhau =", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauNotEqualTo(String value) {
            addCriterion("matKhau <>", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauGreaterThan(String value) {
            addCriterion("matKhau >", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauGreaterThanOrEqualTo(String value) {
            addCriterion("matKhau >=", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauLessThan(String value) {
            addCriterion("matKhau <", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauLessThanOrEqualTo(String value) {
            addCriterion("matKhau <=", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauLike(String value) {
            addCriterion("matKhau like", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauNotLike(String value) {
            addCriterion("matKhau not like", value, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauIn(List<String> values) {
            addCriterion("matKhau in", values, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauNotIn(List<String> values) {
            addCriterion("matKhau not in", values, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauBetween(String value1, String value2) {
            addCriterion("matKhau between", value1, value2, "matkhau");
            return (Criteria) this;
        }

        public Criteria andMatkhauNotBetween(String value1, String value2) {
            addCriterion("matKhau not between", value1, value2, "matkhau");
            return (Criteria) this;
        }

        public Criteria andTrangthaiIsNull() {
            addCriterion("trangThai is null");
            return (Criteria) this;
        }

        public Criteria andTrangthaiIsNotNull() {
            addCriterion("trangThai is not null");
            return (Criteria) this;
        }

        public Criteria andTrangthaiEqualTo(Boolean value) {
            addCriterion("trangThai =", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiNotEqualTo(Boolean value) {
            addCriterion("trangThai <>", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiGreaterThan(Boolean value) {
            addCriterion("trangThai >", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiGreaterThanOrEqualTo(Boolean value) {
            addCriterion("trangThai >=", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiLessThan(Boolean value) {
            addCriterion("trangThai <", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiLessThanOrEqualTo(Boolean value) {
            addCriterion("trangThai <=", value, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiIn(List<Boolean> values) {
            addCriterion("trangThai in", values, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiNotIn(List<Boolean> values) {
            addCriterion("trangThai not in", values, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiBetween(Boolean value1, Boolean value2) {
            addCriterion("trangThai between", value1, value2, "trangthai");
            return (Criteria) this;
        }

        public Criteria andTrangthaiNotBetween(Boolean value1, Boolean value2) {
            addCriterion("trangThai not between", value1, value2, "trangthai");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KhachHang
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 04 22:35:50 ICT 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KhachHang
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}