package com.LTNC.LTNC_Java.model;

public class LienHe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.IdLienHe
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idlienhe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.Ho
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String ho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.Ten
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.Email
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.SDT
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String sdt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.NoiDung
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String noidung;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LienHe.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idkhach;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.IdLienHe
     *
     * @return the value of LienHe.IdLienHe
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdlienhe() {
        return idlienhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.IdLienHe
     *
     * @param idlienhe the value for LienHe.IdLienHe
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdlienhe(Integer idlienhe) {
        this.idlienhe = idlienhe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.Ho
     *
     * @return the value of LienHe.Ho
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getHo() {
        return ho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.Ho
     *
     * @param ho the value for LienHe.Ho
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setHo(String ho) {
        this.ho = ho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.Ten
     *
     * @return the value of LienHe.Ten
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.Ten
     *
     * @param ten the value for LienHe.Ten
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.Email
     *
     * @return the value of LienHe.Email
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.Email
     *
     * @param email the value for LienHe.Email
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.SDT
     *
     * @return the value of LienHe.SDT
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getSdt() {
        return sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.SDT
     *
     * @param sdt the value for LienHe.SDT
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.NoiDung
     *
     * @return the value of LienHe.NoiDung
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getNoidung() {
        return noidung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.NoiDung
     *
     * @param noidung the value for LienHe.NoiDung
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LienHe.idKhach
     *
     * @return the value of LienHe.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdkhach() {
        return idkhach;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LienHe.idKhach
     *
     * @param idkhach the value for LienHe.idKhach
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdkhach(Integer idkhach) {
        this.idkhach = idkhach;
    }
}