package com.LTNC.LTNC_Java.model;

public class LoaiSp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoaiSp.idLoai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idloai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoaiSp.tenLoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String tenloaisp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoaiSp.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Boolean trangthai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LoaiSp.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iduser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoaiSp.idLoai
     *
     * @return the value of LoaiSp.idLoai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdloai() {
        return idloai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoaiSp.idLoai
     *
     * @param idloai the value for LoaiSp.idLoai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdloai(Integer idloai) {
        this.idloai = idloai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoaiSp.tenLoaiSp
     *
     * @return the value of LoaiSp.tenLoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTenloaisp() {
        return tenloaisp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoaiSp.tenLoaiSp
     *
     * @param tenloaisp the value for LoaiSp.tenLoaiSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTenloaisp(String tenloaisp) {
        this.tenloaisp = tenloaisp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoaiSp.trangThai
     *
     * @return the value of LoaiSp.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Boolean getTrangthai() {
        return trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoaiSp.trangThai
     *
     * @param trangthai the value for LoaiSp.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTrangthai(Boolean trangthai) {
        this.trangthai = trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LoaiSp.idUser
     *
     * @return the value of LoaiSp.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LoaiSp.idUser
     *
     * @param iduser the value for LoaiSp.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
}