package com.LTNC.LTNC_Java.model;

public class SanPham {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idsp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.ten
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String ten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.gia
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Double gia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.giaKm
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Double giakm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer trangthai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.idLoai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idloai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.idThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idthuonghieu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.soLuong
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer soluong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.trangThaiMieuTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String trangthaimieuta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.anhDaiDien
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String anhdaidien;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.MieuTaSanPhamNoiBat
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String mieutasanphamnoibat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.idSp
     *
     * @return the value of SanPham.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdsp() {
        return idsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.idSp
     *
     * @param idsp the value for SanPham.idSp
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdsp(Integer idsp) {
        this.idsp = idsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.ten
     *
     * @return the value of SanPham.ten
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTen() {
        return ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.ten
     *
     * @param ten the value for SanPham.ten
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTen(String ten) {
        this.ten = ten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.gia
     *
     * @return the value of SanPham.gia
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Double getGia() {
        return gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.gia
     *
     * @param gia the value for SanPham.gia
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setGia(Double gia) {
        this.gia = gia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.giaKm
     *
     * @return the value of SanPham.giaKm
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Double getGiakm() {
        return giakm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.giaKm
     *
     * @param giakm the value for SanPham.giaKm
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setGiakm(Double giakm) {
        this.giakm = giakm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.trangThai
     *
     * @return the value of SanPham.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getTrangthai() {
        return trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.trangThai
     *
     * @param trangthai the value for SanPham.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTrangthai(Integer trangthai) {
        this.trangthai = trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.idLoai
     *
     * @return the value of SanPham.idLoai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdloai() {
        return idloai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.idLoai
     *
     * @param idloai the value for SanPham.idLoai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdloai(Integer idloai) {
        this.idloai = idloai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.idThuongHieu
     *
     * @return the value of SanPham.idThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdthuonghieu() {
        return idthuonghieu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.idThuongHieu
     *
     * @param idthuonghieu the value for SanPham.idThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdthuonghieu(Integer idthuonghieu) {
        this.idthuonghieu = idthuonghieu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.idUser
     *
     * @return the value of SanPham.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.idUser
     *
     * @param iduser the value for SanPham.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.soLuong
     *
     * @return the value of SanPham.soLuong
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getSoluong() {
        return soluong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.soLuong
     *
     * @param soluong the value for SanPham.soLuong
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.trangThaiMieuTa
     *
     * @return the value of SanPham.trangThaiMieuTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTrangthaimieuta() {
        return trangthaimieuta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.trangThaiMieuTa
     *
     * @param trangthaimieuta the value for SanPham.trangThaiMieuTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTrangthaimieuta(String trangthaimieuta) {
        this.trangthaimieuta = trangthaimieuta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.anhDaiDien
     *
     * @return the value of SanPham.anhDaiDien
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getAnhdaidien() {
        return anhdaidien;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.anhDaiDien
     *
     * @param anhdaidien the value for SanPham.anhDaiDien
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setAnhdaidien(String anhdaidien) {
        this.anhdaidien = anhdaidien;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.MieuTaSanPhamNoiBat
     *
     * @return the value of SanPham.MieuTaSanPhamNoiBat
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getMieutasanphamnoibat() {
        return mieutasanphamnoibat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.MieuTaSanPhamNoiBat
     *
     * @param mieutasanphamnoibat the value for SanPham.MieuTaSanPhamNoiBat
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setMieutasanphamnoibat(String mieutasanphamnoibat) {
        this.mieutasanphamnoibat = mieutasanphamnoibat;
    }
}