package com.LTNC.LTNC_Java.model;

public class SanPhamWithBLOBs extends SanPham {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.moTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String mota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SanPham.chiTiet
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String chitiet;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.moTa
     *
     * @return the value of SanPham.moTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getMota() {
        return mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.moTa
     *
     * @param mota the value for SanPham.moTa
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setMota(String mota) {
        this.mota = mota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SanPham.chiTiet
     *
     * @return the value of SanPham.chiTiet
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getChitiet() {
        return chitiet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SanPham.chiTiet
     *
     * @param chitiet the value for SanPham.chiTiet
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setChitiet(String chitiet) {
        this.chitiet = chitiet;
    }
}