package com.LTNC.LTNC_Java.model;

public class ThuongHieu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ThuongHieu.idThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idthuonghieu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ThuongHieu.tenThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String tenthuonghieu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ThuongHieu.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iduser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ThuongHieu.idThuongHieu
     *
     * @return the value of ThuongHieu.idThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdthuonghieu() {
        return idthuonghieu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ThuongHieu.idThuongHieu
     *
     * @param idthuonghieu the value for ThuongHieu.idThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdthuonghieu(Integer idthuonghieu) {
        this.idthuonghieu = idthuonghieu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ThuongHieu.tenThuongHieu
     *
     * @return the value of ThuongHieu.tenThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTenthuonghieu() {
        return tenthuonghieu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ThuongHieu.tenThuongHieu
     *
     * @param tenthuonghieu the value for ThuongHieu.tenThuongHieu
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTenthuonghieu(String tenthuonghieu) {
        this.tenthuonghieu = tenthuonghieu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ThuongHieu.idUser
     *
     * @return the value of ThuongHieu.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ThuongHieu.idUser
     *
     * @param iduser the value for ThuongHieu.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }
}