package com.LTNC.LTNC_Java.model;

import java.util.Date;

public class TinTuc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TinTuc.idTin
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer idtin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TinTuc.tieuDe
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String tieude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TinTuc.anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String anh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TinTuc.ngayTao
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Date ngaytao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TinTuc.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TinTuc.noiDung
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String noidung;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TinTuc.idTin
     *
     * @return the value of TinTuc.idTin
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIdtin() {
        return idtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TinTuc.idTin
     *
     * @param idtin the value for TinTuc.idTin
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIdtin(Integer idtin) {
        this.idtin = idtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TinTuc.tieuDe
     *
     * @return the value of TinTuc.tieuDe
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTieude() {
        return tieude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TinTuc.tieuDe
     *
     * @param tieude the value for TinTuc.tieuDe
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTieude(String tieude) {
        this.tieude = tieude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TinTuc.anh
     *
     * @return the value of TinTuc.anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getAnh() {
        return anh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TinTuc.anh
     *
     * @param anh the value for TinTuc.anh
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setAnh(String anh) {
        this.anh = anh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TinTuc.ngayTao
     *
     * @return the value of TinTuc.ngayTao
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Date getNgaytao() {
        return ngaytao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TinTuc.ngayTao
     *
     * @param ngaytao the value for TinTuc.ngayTao
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setNgaytao(Date ngaytao) {
        this.ngaytao = ngaytao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TinTuc.idUser
     *
     * @return the value of TinTuc.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TinTuc.idUser
     *
     * @param iduser the value for TinTuc.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TinTuc.noiDung
     *
     * @return the value of TinTuc.noiDung
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getNoidung() {
        return noidung;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TinTuc.noiDung
     *
     * @param noidung the value for TinTuc.noiDung
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setNoidung(String noidung) {
        this.noidung = noidung;
    }
}