package com.LTNC.LTNC_Java.model;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer iduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.hoTen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String hoten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.tenDangNhap
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String tendangnhap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.matKhau
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private String matkhau;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.quyen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Integer quyen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Users.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    private Boolean trangthai;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.idUser
     *
     * @return the value of Users.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getIduser() {
        return iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.idUser
     *
     * @param iduser the value for Users.idUser
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setIduser(Integer iduser) {
        this.iduser = iduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.hoTen
     *
     * @return the value of Users.hoTen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getHoten() {
        return hoten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.hoTen
     *
     * @param hoten the value for Users.hoTen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.tenDangNhap
     *
     * @return the value of Users.tenDangNhap
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getTendangnhap() {
        return tendangnhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.tenDangNhap
     *
     * @param tendangnhap the value for Users.tenDangNhap
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.matKhau
     *
     * @return the value of Users.matKhau
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public String getMatkhau() {
        return matkhau;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.matKhau
     *
     * @param matkhau the value for Users.matKhau
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.quyen
     *
     * @return the value of Users.quyen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Integer getQuyen() {
        return quyen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.quyen
     *
     * @param quyen the value for Users.quyen
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setQuyen(Integer quyen) {
        this.quyen = quyen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Users.trangThai
     *
     * @return the value of Users.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public Boolean getTrangthai() {
        return trangthai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Users.trangThai
     *
     * @param trangthai the value for Users.trangThai
     *
     * @mbg.generated Sat Dec 04 22:35:50 ICT 2021
     */
    public void setTrangthai(Boolean trangthai) {
        this.trangthai = trangthai;
    }
}